const episodes=[
{n:'06',title:'Mental health during your next big thing',category:'purpose',label:'Purpose & life',description:'Career changes take a toll. A conversation about paying attention to your mental health along the way.',video:'U3p3W5IgIak',apple:'1000779134888'},
{n:'05',title:'Embrace the messy. Start the business.',category:'business',label:'Business',description:'Serial entrepreneur Diana Paquet joins the guys to talk about getting started before you have it all figured out.',video:'EZj1BC3QTcc',apple:'1000778238884'},
{n:'04',title:'Ikigai: find your reason for being',category:'purpose',label:'Purpose & life',description:'What gives your work meaning? Explore how your career can connect with what matters to you.',video:'zMqVf0M1oN4',apple:'1000774726316'},
{n:'03',title:'Could a franchise be your next move?',category:'business',label:'Business',description:'Andy Cohen talks about finding and evaluating franchise opportunities, and what it takes to get started.',video:'oC5czGMj8iQ',apple:'1000772070800'},
{n:'02',title:'Networking 101, without the awkward',category:'career',label:'Career',description:'Making a lasting impression in person and online. Practical conversation for your next career move.',video:'WMdVdvZNUlo',apple:'1000756178177'},
{n:'01',title:'Hello world. Meet your next big thing.',category:'career',label:'Career',description:'Get to know the show and the guys. Where we came from, what we’re asking, and why we hit record.',video:'OlTWxTSESzE',apple:'1000756170017'}
];
const grid=document.querySelector('#episode-grid'), dialog=document.querySelector('#player');
function render(filter='all'){const shown=episodes.filter(e=>filter==='all'||e.category===filter);grid.innerHTML=shown.map(e=>`<article class="episode"><div class="episode-art"><span>YOUR NEXT<br>BIG THING<br><br>SEASON 01</span><strong>${e.n}</strong></div><div class="episode-body"><span class="category">${e.label.toUpperCase()} / EPISODE ${e.n}</span><h3>${e.title}</h3><p>${e.description}</p><div class="episode-actions"><button data-episode="${e.n}" data-mode="audio" aria-label="Listen to ${e.title}">▶ Listen</button><button data-episode="${e.n}" data-mode="video" aria-label="Watch ${e.title}">Watch episode</button></div></div></article>`).join('');document.querySelector('#result-count').textContent=`${shown.length} episodes shown`;}
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render(b.dataset.filter)}));
grid.addEventListener('click',event=>{const b=event.target.closest('[data-episode]');if(!b)return;const e=episodes.find(x=>x.n===b.dataset.episode),video=b.dataset.mode==='video';document.querySelector('#player-label').textContent=`S1 E${Number(e.n)} · ${e.title}`;const src=video?`https://www.youtube-nocookie.com/embed/${e.video}`:`https://embed.podcasts.apple.com/us/podcast/id1873442294?i=${e.apple}&theme=light`;document.querySelector('#player-content').innerHTML=`<iframe title="${video?'Video':'Audio'} episode player" src="${src}" height="${video?'450':'175'}" allow="autoplay; encrypted-media; fullscreen" allowfullscreen></iframe>`;document.querySelector('#player-fallback').innerHTML=`Prefer to open the episode directly? <a href="${video?`https://www.youtube.com/watch?v=${e.video}`:`https://podcasts.apple.com/us/podcast/id1873442294?i=${e.apple}`}" target="_blank" rel="noopener">Open on ${video?'YouTube':'Apple Podcasts'}</a>`;dialog.showModal();});
document.querySelector('#close-player').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{document.querySelector('#player-content').innerHTML=''});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});render();
